<?php

namespace app\tests\functional;
use app\models\City;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../models/City.php';

/**
 * Test class for City.
 * Generated by PHPUnit on 2010-11-30 at 17:45:44.
 */
class CityTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var City
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new City;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testPopulate().
	 */
	public function testPopulate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test__toString().
	 */
	public function test__toString() {
		$this->object->setName('city');
		$this->assertEquals('City', (string)$this->object);
	}

	/**
	 * @todo Implement testSetCountry().
	 */
	public function testSetCountry() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCountry().
	 */
	public function testGetCountry() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetState().
	 */
	public function testSetState() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetState().
	 */
	public function testGetState() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetName().
	 */
	public function testSetName() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetName().
	 */
	public function testGetName() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
