<?php

namespace app\tests\functional\app\models;

use app\models\Place;
use app\models\Category;

/**
 * Test class for Place.
 * Generated by PHPUnit on 2010-12-01 at 13:13:49.
 */
class PlaceTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Place
	 */
	protected $object;

	protected function setUp() {
		$this->object = new Place;
	}

	protected function tearDown() {
		unset($this->object);
	}

	public function testPopulate() {
		$data = new \stdClass();
		$category = new Category();

		$data->id = 123;
		$data->name = "Chegamos!";
		$data->averageRating = 4;
		$data->reviewCount = 3;
		$data->category = $category;
		$data->subcategory = "SubCategory";
		$data->address = "Address";
		$data->point = "-23.529366,-47.467117";
		$data->mainUrl = "http://chegamos.com/";
		$data->otherUrl = "http://chegamos.com/";
		$data->iconUrl = "";
		$data->description = "Description";
		$data->created = "01/12/2010 16:19";
		$data->phone = "11 2222-3333";
		$data->visitors = array('user1','user2','user3');
		$data->placeInfo = "Place Info?";
		$data->numVisitors = 1024;
		$data->numPhotos = 5;

		$this->object->populate($data);
		
	}

	public function testSetGetId() {
		$this->object->setId(123);
		$this->assertEquals(123, $this->object->getId());
	}

	public function testSetGetNumVisitors() {
		$this->object->setNumVisitors(1024);
		$this->assertEquals(1024, $this->object->getNumVisitors());
	}

	public function testSetGetNumPhotos() {
		$this->object->setNumPhotos(5);
		$this->assertEquals(5, $this->object->getNumPhotos());
	}

	public function testSetGetName() {
		$this->object->setName("Chegamos!");
		$this->assertEquals("Chegamos!", $this->object->getName());
	}

	public function testSetGetCreated() {
		$this->object->setCreated("01/12/2010 13:27");
		$this->assertEquals("01/12/2010 13:27", $this->object->getCreated());
	}

	public function testSetGetPlaceInfo() {
		$this->object->setPlaceInfo("Place Info?");
		$this->assertEquals("Place Info?", $this->object->getPlaceInfo());
	}

	public function testSetGetPhone() {
		$this->object->setPhone("Place Info?");
		$this->assertEquals("Place Info?", $this->object->getPhone());
	}

	public function testSetGetDescription() {
		$this->object->setDescription("Description");
		$this->assertEquals("Description", $this->object->getDescription());
	}

	public function testSetGetAverageRating() {
		$this->object->setAverageRating(1);
		$this->assertEquals(1, $this->object->getAverageRating());
		$this->object->setAverageRating(2);
		$this->assertEquals(2, $this->object->getAverageRating());
		$this->object->setAverageRating(3);
		$this->assertEquals(3, $this->object->getAverageRating());
		$this->object->setAverageRating(4);
		$this->assertEquals(4, $this->object->getAverageRating());
		$this->object->setAverageRating(5);
		$this->assertEquals(5, $this->object->getAverageRating());
	}

//	public function testSetGetAverageRatingString() {
//		$this->object->setAverageRatingString("String");
//		$this->assertEquals("String", $this->object->getAverageRatingString());
//	}

	public function testSetGetReviewCount() {
		$this->object->setReviewCount(3);
		$this->assertEquals(3, $this->object->getReviewCount());
	}

	public function testSetGetCategory() {
		$this->object->setCategory("String");
		$this->assertEquals("String", $this->object->getCategory());
	}

	public function testSetGetAddress() {
		$this->object->setAddress("Address");
		$this->assertEquals("Address", $this->object->getAddress());
	}

	public function testSetGetPoint() {
		$this->object->setPoint("-23.529366,-47.467117");
		$this->assertEquals("-23.529366,-47.467117", $this->object->getPoint());
	}

	public function testSetGetMainUrl() {
		$this->object->setMainUrl("http://chegamos.com/");
		$this->assertEquals("http://chegamos.com/", $this->object->getMainUrl());
	}

	public function testSetGetOtherUrl() {
		$this->object->setOtherUrl("http://chegamos.com/");
		$this->assertEquals("http://chegamos.com/", $this->object->getOtherUrl());
	}

	public function testSetGetIconUrl() {
		$this->object->setIconUrl("http://chegamos.com/img/logo.jpg");
		$this->assertEquals("http://chegamos.com/img/logo.jpg", $this->object->getIconUrl());
	}

	public function testGetRouteUrl() {

		//$this->assertEquals("http://chegamos.com/img/logo.jpg", $this->object->getIconUrl());
	}

}

?>
